### ISSUE TITLE
Is there a way to provider a different table name than `account_identities`?

### ISSUE THREAD

**Issue by chika-kasymov** [janko/rodauth-omniauth#1]
I've got two `rodauth` configurations with different tables. For that reason, I need to create two `X_account_identities` tables as well. It'll be great if there is a way to add a prefix or provide a completely different table name.

**Comment by janko** [comment]
Yes, you can set `omniauth_identities_table` in your Rodauth configuration, e.g:

```rb
class RodauthAdmin < Rodauth::Auth
  configure do
    omniauth_identities_table :admin_identities
  end
end
```

I see now that I forgot to document it, I'll add that.

**Comment by chika-kasymov** [comment]
That's awesome! In my case, I also needed to customize the `omniauth_identities_account_id_column` and that resolved my issue. Thanks for your help!
