### ISSUE TITLE
"identities" association not found

### ISSUE THREAD

**Issue by Dainii** [janko/rodauth-omniauth#10]
Hello,

With my current project, the `identities` association does not work, but the rest of the authentication works like a charm, and the entry in the `account_identities` table is present.

Version info:
* ruby 3.2.1
* rails 7.0.4.2
* rodauth 2.28.0
* rodauth-model 0.2.1
* rodauth-omniauth 0.3.1
* omniauth 2.0.4

Account model

```ruby
# frozen_string_literal: true

class Account < ApplicationRecord
  include Rodauth::Rails.model

  enum :status, unverified: 1, verified: 2, closed: 3
end
```

When I try to access the identities through `Account.first.identities`, I got

```
/home/user/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activemodel-7.0.4.2/lib/active_model/attribute_methods.rb:458:in `method_missing': undefined method `identities' for #<Account id: 5, status: "verified", email: "user@email.com", password_hash: nil> (NoMethodError)"
```

I put a debug string after [this line](https://github.com/janko/rodauth-omniauth/blob/481be62e4f5c20c9c1138d7cd272a5125d65d4f7/lib/rodauth/features/omniauth.rb#L205) to be sure that `if defined?(Rodauth::Model)` is true and that's the case.

Other association like `verification_key` works fine.

**Comment by janko** [comment]
Hello, thanks for reporting. I'm trying to find a scenario in which this error can happen, but I'm not coming up with anything concrete. Any chance you could reproduce it in a fresh Rails app that you can share?

**Comment by Dainii** [comment]
Hello, thank you for the answer.

I created a rails app [here](https://github.com/Dainii/rodauth-test). I just need to copy the /.env.exampe to /.env and set the discord client id and secret to test.

With this setup, I am able to login through discord, the account is created, the `account_identities` entry too, but i'm still not able to call the `.identities` relation.

**Comment by janko** [comment]
There was a mistake in the association registration, so it never worked 🙈 In the rodauth-demo-rails app it only worked because there was a leftover `has_many :identities` association defined from when the OmniAuth integration was implemented manually. I [fixed](https://github.com/janko/rodauth-omniauth/commit/375eb4a9ed76263b2f8ebb556ad883c2089c0321) it now and released a new version.

**Comment by Dainii** [comment]
Hello @janko 
Thank you for this ;)
