### ISSUE TITLE
Correct URLs generated when using "prefix" in rodauth

### ISSUE THREAD

**Issue by 34code** [janko/rodauth-omniauth#12]
Hi,

It seems when using `prefix "/user"` in `app/misc/rodauth_main.rb`, the routes generated for omniauth add an additional /user prefix and do not work. 

The generated routes look like the following:
`/user/user/auth/facebook/callback`

and I get the following error:

`'No route matches [GET] "/user/user/auth/facebook/callback"'`

perhaps the prefix is also applying somewhere it should not?

**Comment by janko** [comment]
I couldn't reproduce this on the [Rails demo app](https://github.com/janko/rodauth-demo-rails); I set `prefix "/user"` in `rodauth_main.rb`, and `rodauth.omniauth_callback_path(:github)` returned `/user/auth/github/callback`, not `/user/user/auth/github/callback`. Here is a self-contained example with plain Rodauth showing this behavior:

```rb
require "sequel"
require "roda"
require "omniauth-github"
require "rack/test"

DB = Sequel.sqlite

class App < Roda
  plugin :rodauth do
    enable :omniauth
    omniauth_provider :github, "key", "secret"
    prefix "/user"
  end

  route do |r|
    r.root do
      rodauth.omniauth_callback_path(:github)
    end
  end
end

session = Rack::Test::Session.new(App)
session.get("/").body #=> "/user/auth/github/callback"
```

**Comment by 34code** [comment]
strange, you are right.. must be something else in my code. Anyway, I was able to get mine working without the prefix.. I can live without the prefix feature. Thanks for this awesome gem to help explore all the features of rodauth!

**Comment by xtr3me** [comment]
I have the same issue with the facebook integration and traced it to the following line in the omniauth-facebook gem:
https://github.com/simi/omniauth-facebook/blob/69872e731e3372cf51b8274ce0048139a8102b54/lib/omniauth/strategies/facebook.rb#L88

From what I can see:
full_host -> scheme + domain + port
script_name -> rodauth prefix
callback_path -> rodauth prefix + callback path

When i give the callback_url option to the facebook provider like this:
```
omniauth_provider :facebook, "client_id", "secret", scope: "email", callback_url: "http://localhost:3000/sso/auth/facebook/callback"
```

Everything works correctly.

**Comment by janko** [comment]
I tested omniauth-github with the path prefix, and it worked correctly – the prefix wasn't duplicated.

It seems this is a bug in omniauth-facebook. It generates the callback URL from `full_host + script_name + callback_path`, but OmniAuth's `callback_path` already [adds](https://github.com/omniauth/omniauth/blob/a13cd110beb9538ea51be6c614bf43351c3f4e95/lib/omniauth/strategy.rb#L450) `script_name`. It appears this was [fixed](https://github.com/simi/omniauth-facebook/pull/380) on master, but a new release of omniauth-facebook hasn't yet gone out.

rodauth-omniauth relies on `SCRIPT_NAME` env variable for its automatic routing of the OmniAuth app, and it seems some reverse proxy setups also use it. So, for the time being I recommend pulling omniauth-facebook from GitHub.
