### ISSUE TITLE
Version dependency problems

### ISSUE THREAD

**Issue by Tripple-A** [janko/rodauth-omniauth#8]
Hi, When trying to use the `omniauth-google_oauth2` gem as stated in the documentation, along with the `rodauth-omniauth` gem. The following errors occur due to version dependencies of `omniauth`

```
Bundler could not find compatible versions for gem "omniauth":
  In snapshot (Gemfile.lock):
    omniauth (= 1.9.2)

  In Gemfile:
    omniauth-google_oauth2 (~> 0.1.5) was resolved to 0.1.5, which depends on
      omniauth (~> 1.0)

    rodauth-omniauth was resolved to 0.3.1, which depends on
      omniauth (~> 2.0)
```
A more compatible gem is [this](https://rubygems.org/gems/omniauth-google-oauth2). If you would like to effect this change in the documentation, I don't mind updating it and creating a PR for it. Thanks

**Comment by janko** [comment]
Yes, if the docs don't already mention that rodauth-omniauth requires OmniAuth 2.0, it would be good to add it there, thanks!

**Comment by Tripple-A** [comment]
Alright, should I also replace the gem used in the example, with the compatible one?

**Comment by janko** [comment]
Updated in https://github.com/janko/rodauth-omniauth/pull/9.
